apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app
  namespace: argocd
spec:
  destination:
    namespace: core
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/gitops/overlays/prod
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true